global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'caculinha-bi'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
